import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <-- generated by `flutterfire configure`
import 'screens/login_screen.dart';
import 'screens/dashboard_screen.dart';
import 'services/auth_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const SmartHealthGloveApp());
}

class SmartHealthGloveApp extends StatefulWidget {
  const SmartHealthGloveApp({super.key});

  @override
  State<SmartHealthGloveApp> createState() => _SmartHealthGloveAppState();
}

class _SmartHealthGloveAppState extends State<SmartHealthGloveApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Health Glove',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF2563EB)),
        useMaterial3: true,
      ),
      home: AuthService.instance.userStreamBuilder(
        loggedIn: const DashboardScreen(),
        loggedOut: const LoginScreen(),
      ),
    );
  }
}
